version: '3'

services:
 
  #mysql
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: carcare
      MYSQL_DATABASE: carcare
    ports:
      - '3307:3306'
    networks:
      - dev_networks

  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: carcare
    networks:
      - dev_networks


networks:
  dev_networks:
  
volumes:
  db_data:



