
version: '3'
 
services:
  db:
    image: mysql
    container_name: carcaredb
    environment:
      MYSQL_ROOT_PASSWORD: carcare
      MYSQL_DATABASE: carcare
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmincarcare
    links:
      - carecaredb:db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata: